#!/usr/bin/env bash
# =============================================================================
# Build the AI Adoption Tracker AIR-GAP bundle.
#
# Run this on a machine WITH internet (and node_modules installed in
# src/frontend). It produces a single self-contained zip that installs and runs
# with NO network on the target box.
#
# Output: deployment/dist/ai-tracker-airgap.zip   (dist/ is gitignored)
#
# What it does (nothing here touches the running dev servers or the live DB):
#   1. Stage the backend source (app.py, db.py, models.py, schema.sql, routers,
#      llm/, reports/, search/) — EXCLUDING tracker.db*, tests, caches, and the
#      dangerous DEV-only seed.py.
#   2. Drop in serve.py (the single-process UI+API entrypoint).
#   3. Build the frontend (vite build) into web/  — static, no Node at runtime.
#   4. Vendor a Python wheelhouse for the TARGET platform (pip download).
#   5. Generate requirements.lock.txt from the vendored wheels.
#   6. Copy scripts, systemd template, env.example, docs, VERSION.
#   7. Zip it.
#
# IMPORTANT — target platform:
#   Wheels with C extensions (pydantic-core, jiter) are platform+python
#   specific. Defaults below target Linux x86_64 / CPython 3.11 (the typical
#   air-gap server). If your box differs, override:
#       TARGET_PLATFORM=manylinux2014_aarch64 TARGET_PYVER=312 ./make_bundle.sh
#   The cleanest guarantee is to run this ON a machine matching the target's
#   OS/arch/python.
# =============================================================================
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$DEPLOY_DIR/.." && pwd)"
BACKEND_SRC="$REPO_ROOT/src/backend"
FRONTEND_SRC="$REPO_ROOT/src/frontend"
BUNDLE_TEMPLATE="$DEPLOY_DIR/bundle"

# --- Tunables ---------------------------------------------------------------
TARGET_PLATFORM="${TARGET_PLATFORM:-manylinux2014_x86_64}"
TARGET_PYVER="${TARGET_PYVER:-311}"
PIP_IMPL="${PIP_IMPL:-cp}"   # cp = CPython
NAME="ai-tracker-airgap"

# Pinned top-level deps (transitive resolved automatically by pip download).
# Versions match what the project is developed against.
PINS=(
  "fastapi==0.121.2"
  "uvicorn==0.34.3"
  "openai==2.8.1"
  "anthropic==0.71.0"
  "pydantic==2.12.5"
)

# --- Staging ----------------------------------------------------------------
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
ROOT="$STAGE/$NAME"
mkdir -p "$ROOT/app" "$ROOT/web" "$ROOT/wheels" "$ROOT/scripts" "$ROOT/systemd"

echo "==> [1/7] Staging backend source"
# Copy backend, excluding the live DB, caches, tests, and DEV-only seed.py.
RSYNC_EXCLUDES=(
  --exclude 'tracker.db' --exclude 'tracker.db-wal' --exclude 'tracker.db-shm'
  --exclude 'tracker.db.bak' --exclude '*.db'
  --exclude '__pycache__/' --exclude '*.pyc'
  --exclude '.pytest_cache/' --exclude 'tests/'
  --exclude 'seed.py' --exclude 'run.sh' --exclude 'pyproject.toml'
)
if command -v rsync >/dev/null 2>&1; then
  rsync -a "${RSYNC_EXCLUDES[@]}" "$BACKEND_SRC/" "$ROOT/app/"
else
  # Fallback without rsync: copy then prune.
  cp -R "$BACKEND_SRC/." "$ROOT/app/"
  rm -f  "$ROOT/app/tracker.db" "$ROOT/app/tracker.db-wal" "$ROOT/app/tracker.db-shm" \
         "$ROOT/app/tracker.db.bak" "$ROOT/app/seed.py" "$ROOT/app/run.sh" \
         "$ROOT/app/pyproject.toml"
  find "$ROOT/app" -name '__pycache__' -type d -prune -exec rm -rf {} +
  find "$ROOT/app" -name '*.pyc' -delete
  rm -rf "$ROOT/app/.pytest_cache" "$ROOT/app/tests"
fi

echo "==> [2/7] Adding serve.py entrypoint"
cp "$BUNDLE_TEMPLATE/serve.py" "$ROOT/app/serve.py"

echo "==> [3/7] Building frontend (vite build -> web/)"
if [[ ! -d "$FRONTEND_SRC/node_modules" ]]; then
  echo "ERROR: $FRONTEND_SRC/node_modules missing. Run 'npm install' there first." >&2
  exit 1
fi
( cd "$FRONTEND_SRC" && npx vite build --outDir "$ROOT/web" --emptyOutDir )

echo "==> [4/7] Vendoring Python wheelhouse"
echo "    target: platform=$TARGET_PLATFORM python=$TARGET_PYVER impl=$PIP_IMPL"
pip download --only-binary=:all: \
  --platform "$TARGET_PLATFORM" \
  --python-version "$TARGET_PYVER" \
  --implementation "$PIP_IMPL" \
  "${PINS[@]}" \
  -d "$ROOT/wheels"

echo "==> [5/7] Generating requirements.lock.txt from wheelhouse"
python3 - "$ROOT/wheels" "$ROOT/requirements.lock.txt" <<'PY'
import sys, pathlib, re
wheels = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])
pins = []
for w in sorted(wheels.glob("*.whl")):
    # <name>-<version>-<pytag>-<abitag>-<platformtag>.whl
    name, version = w.name.split("-")[0], w.name.split("-")[1]
    pins.append(f"{name.replace('_','-')}=={version}")
out.write_text(
    "# Generated by make_bundle.sh from the vendored wheelhouse. Pinned.\n"
    + "\n".join(sorted(set(pins), key=str.lower)) + "\n"
)
print(f"    wrote {out.name} ({len(set(pins))} pins)")
PY

echo "==> [6/7] Copying scripts, systemd, docs, env, VERSION"
cp "$BUNDLE_TEMPLATE/scripts/"*.sh "$ROOT/scripts/"
chmod +x "$ROOT/scripts/"*.sh
cp "$BUNDLE_TEMPLATE/systemd/ai-tracker.service.template" "$ROOT/systemd/"
cp "$BUNDLE_TEMPLATE/env.example" "$ROOT/env.example"
cp "$BUNDLE_TEMPLATE/VERSION" "$ROOT/VERSION"
# Operator-facing docs travel inside the bundle.
cp "$DEPLOY_DIR/README_HUMAN.md"  "$ROOT/README_HUMAN.md"
cp "$DEPLOY_DIR/DB_LIFECYCLE.md"  "$ROOT/DB_LIFECYCLE.md"
cp "$DEPLOY_DIR/UPGRADING.md"     "$ROOT/UPGRADING.md"

echo "==> [7/7] Zipping bundle"
mkdir -p "$DEPLOY_DIR/dist"
OUT="$DEPLOY_DIR/dist/$NAME.zip"
rm -f "$OUT"
( cd "$STAGE" && zip -rq "$OUT" "$NAME" )

echo
echo "Bundle built: $OUT"
echo "  size:    $(du -h "$OUT" | cut -f1)"
echo "  wheels:  $(ls "$ROOT/wheels" | wc -l | tr -d ' ')"
echo "  version: $(cat "$ROOT/VERSION")"
echo
echo "Ship the zip to the air-gap box, then:"
echo "  unzip $NAME.zip && cd $NAME"
echo "  ./scripts/install.sh"
echo "  cp env.example env && edit env"
echo "  ./scripts/start.sh"
